### ISSUE TITLE
Fix author links in the blog

### ISSUE THREAD

**Issue by jvendrell** [MarsBased/marsbased-website#58]
## Author link under the title

If an author doesn't have a Twitter account, the author link that appears under the post title takes you to Twitter.com. In cases like that, we should show the author name without link. Also, it should open in a new window.

<img width="737" alt="screen shot 2017-01-27 at 13 36 51" src="https://cloud.githubusercontent.com/assets/7082300/22371153/b5cc60b0-e495-11e6-82d7-c5253b4c37ba.png">

## Author link from the author block

The author link that appears in the "author" block, under the post content, is broken. It should behave like the author link under the title. Also, it should open in a new window.

<img width="728" alt="screen shot 2017-01-27 at 13 37 54" src="https://cloud.githubusercontent.com/assets/7082300/22371181/f68e2340-e495-11e6-8381-a9a77e328d38.png">

## How to remove social accounts

NOTE for @alexrodba:

In order to remove a social account in the authors YML file, you have to delete the whole line, not just the url slug.

Let's say that we want to remove Twitter from your profile.

This would be wrong:

```
author: 'alex'
authorName: 'Àlex Rodríguez Bacardit'
authorImg: '/images/alex-squared.jpg'
authorDescription: 'CMO'
authorEmail: 'alex.rodriguez@marsbased.com'
authorTwitter: ''
authorLinkedIn: 'alexrodba'
authorGithub: 'alexrodba'
```

This would work fine:

```
author: 'alex'
authorName: 'Àlex Rodríguez Bacardit'
authorImg: '/images/alex-squared.jpg'
authorDescription: 'CMO'
authorEmail: 'alex.rodriguez@marsbased.com'
authorLinkedIn: 'alexrodba'
authorGithub: 'alexrodba'

```

**Comment by alexrodba** [comment]
@javierartero we need to have a title attribute to all anchors. For the twitter links you can do something like:

<a href="https://twitter.com/lexrodba" class="icon fa-twitter" title="Àlex Rodríguez Bacardit on Twitter" target="_blank">
                </a>

Copied it from my website, so disregard the font-awesome stuff.

**Comment by jvendrell** [comment]
Hey @alexrodba 

There is a PR where you can give feedback about this issue's implementation:

#93
