### ISSUE TITLE
Add new clients to the Home page

### ISSUE THREAD

**Issue by jvendrell** [MarsBased/marsbased-website#69]
We've worked with some new clients recently that could be added to our Home page ("Some of our clients"):

- Prototyp
- TrustRight
- Aparca&Go
- Cylinder

We should ask them permission to publish their logos on our website and then do it.

**Comment by jvendrell** [comment]
@alexrodba What do you think?

**Comment by alexrodba** [comment]
Adarsh gave permission for Cylinder. I've sent a message to both JL and Pontus.

Pau Seglar real quick, and ask for it. He won't mind.

**Comment by alexrodba** [comment]
@jvendrell: Here's the Cylinder logo: http://cylinder.work/assets/images/cylinder-logo.svg

**Comment by jvendrell** [comment]
JL gave permission for TrustRight, too.

**Comment by alexrodba** [comment]
Yep, for further reference: https://3.basecamp.com/3091551/buckets/1774647/messages/376050648#__recording_376553402

Pontus gave it as well.

![image](https://cloud.githubusercontent.com/assets/6558119/22606728/b9e30414-ea09-11e6-8585-2851685e7212.png)

We just need AparcanGo for now.
