### ISSUE TITLE
Wuaki portfolio

### ISSUE THREAD

**Issue by jvendrell** [MarsBased/marsbased-website#72]

**Comment by jvendrell** [comment]
Hey @javierartero 

This one is ready for you to add the screenshots. Remember adding also the /work small thumbnail, like we did with BCN Startup Map.

**Comment by javierartero** [comment]
https://github.com/MarsBased/marsbased-website/commit/23c5b2e4748a6070c7e5b8d4552c69f006e78cbd

**Comment by jvendrell** [comment]
Merged to master, unpublished, waiting for Wuaki's ok.
