### ISSUE TITLE
Futurisme portfolio

### ISSUE THREAD

**Issue by jvendrell** [MarsBased/marsbased-website#74]

**Comment by alexrodba** [comment]
@jvendrell : just so you know it, you will find this one in the branch of the Naiz portfolio. I wrote them on the same batch and didn't think of separating them.

Needs:

- Probably detaching it from the current branch to a separate one, so we can keep working on the Naiz one until they give permission to publish.
- I will ask for a testimonial, but after we publish. So feel free to publish right away, after your corrections.

**Comment by jvendrell** [comment]
@alexrodba I've created a new branch for the FuTurisme portfolio: featured/futurisme

The content looks great. I've removed the fake testimonial.

@javierartero: it's ready for you to add screenshots!
